import assert from "node:assert/strict";
import test from "node:test";
import zlib from "node:zlib";
import {
  PackageError,
  applyOverlay,
  checkTargetKeys,
  chromiumManifest,
  duplicateTopLevelNames,
  manifestFiles,
  readZip,
  workerEntry,
} from "./package.mjs";

// A manifest shaped like the extension's own, with made-up values, so these tests do not depend on the real one.
const ROOT = {
  manifest_version: 3,
  name: "Example",
  version: "1.2.3",
  icons: { 16: "icons/icon-16.png", 128: "icons/icon-128.png" },
  background: { scripts: ["background/types.js", "background/rss.js", "background/background.js"] },
  content_scripts: [{ matches: ["*://www.example.com/*"], js: ["content/watch.js"], run_at: "document_idle" }],
  action: { default_icon: { 16: "icons/icon-16.png" }, default_title: "Example" },
  options_ui: { page: "options/options.html", open_in_tab: true },
  permissions: ["storage", "menus"],
  host_permissions: ["*://www.example.com/*"],
  browser_specific_settings: { gecko: { id: "example@example.com", strict_min_version: "140.0" } },
};
const OVERLAY = {
  background: { scripts: null, service_worker: "background/service-worker.js" },
  browser_specific_settings: null,
  minimum_chrome_version: "148",
};

test("applyOverlay leaves its arguments alone", () => {
  const base = { a: { b: 1, c: 2 }, list: [1, 2] };
  const overlay = { a: { b: null }, list: [3] };
  const baseBefore = structuredClone(base);
  const overlayBefore = structuredClone(overlay);
  applyOverlay(base, overlay);
  assert.deepEqual(base, baseBefore);
  assert.deepEqual(overlay, overlayBefore);
});

test("applyOverlay merges objects, removes keys set to null, and replaces arrays and scalars", () => {
  const result = applyOverlay({ a: { b: 1, c: 2 }, list: [1, 2], s: "x" }, { a: { b: null, d: 4 }, list: [9], s: "y" });
  assert.deepEqual(result, { a: { c: 2, d: 4 }, list: [9], s: "y" });
});

test("applyOverlay lets an object replace a scalar", () => {
  assert.deepEqual(applyOverlay({ a: 1 }, { a: { b: 2 } }), { a: { b: 2 } });
});

test("chromiumManifest applies the overlay and inherits everything else", () => {
  const manifest = chromiumManifest(ROOT, OVERLAY);
  assert.deepEqual(manifest.background, { service_worker: "background/service-worker.js" });
  assert.equal(manifest.browser_specific_settings, undefined);
  assert.equal(manifest.minimum_chrome_version, "148");
  assert.equal(manifest.version, ROOT.version);
  assert.deepEqual(manifest.host_permissions, ROOT.host_permissions);
  assert.deepEqual(manifest.content_scripts, ROOT.content_scripts);
});

test("chromiumManifest writes the menus permission the way Chrome spells it, once", () => {
  assert.deepEqual(chromiumManifest(ROOT, OVERLAY).permissions, ["storage", "contextMenus"]);
  assert.deepEqual(chromiumManifest({ ...ROOT, permissions: ["storage", "menus", "contextMenus"] }, OVERLAY).permissions, [
    "storage",
    "contextMenus",
  ]);
  assert.equal(chromiumManifest({ ...ROOT, permissions: undefined }, OVERLAY).permissions, undefined);
});

test("workerEntry loads the background scripts, relative to the worker's folder", () => {
  assert.equal(
    workerEntry(ROOT.background.scripts, "background/service-worker.js"),
    '// Generated by tools/package.mjs from "background.scripts" in manifest.json. Do not edit.\n' +
      'importScripts("types.js", "rss.js", "background.js");\n'
  );
  assert.match(workerEntry(["background/a.js", "common/b.js"], "background/sw.js"), /importScripts\("a\.js", "\.\.\/common\/b\.js"\);/);
  assert.match(workerEntry(["background/a.js"], "sw.js"), /importScripts\("background\/a\.js"\);/);
});

test("workerEntry refuses an empty script list and a worker path that is not a .js file", () => {
  assert.throws(() => workerEntry([], "sw.js"), PackageError);
  assert.throws(() => workerEntry(undefined, "sw.js"), PackageError);
  assert.throws(() => workerEntry(["a.js"], "sw.txt"), PackageError);
  assert.throws(() => workerEntry(["a.js"], undefined), PackageError);
});

test("manifestFiles lists every file the manifest refers to, sorted, once", () => {
  assert.deepEqual(manifestFiles(ROOT), [
    "background/background.js",
    "background/rss.js",
    "background/types.js",
    "content/watch.js",
    "icons/icon-128.png",
    "icons/icon-16.png",
    "options/options.html",
  ]);
});

test("manifestFiles also covers a service worker, styles, a popup, a single icon and an options page", () => {
  const files = manifestFiles({
    background: { service_worker: "sw.js", page: "bg.html" },
    content_scripts: [{ js: ["c.js"], css: ["c.css"] }],
    action: { default_icon: "icon.png", default_popup: "popup.html" },
    options_page: "options.html",
  });
  assert.deepEqual(files, ["bg.html", "c.css", "c.js", "icon.png", "options.html", "popup.html", "sw.js"]);
});

test("checkTargetKeys accepts the Firefox manifest and the Chromium manifest derived from it", () => {
  assert.deepEqual(checkTargetKeys("firefox", ROOT, ROOT), []);
  assert.deepEqual(checkTargetKeys("chromium", chromiumManifest(ROOT, OVERLAY), ROOT), []);
});

test("checkTargetKeys reports a Firefox manifest offered as the Chromium one", () => {
  const problems = checkTargetKeys("chromium", ROOT, ROOT).join("\n");
  assert.match(problems, /background\.service_worker is missing/);
  assert.match(problems, /background\.scripts must not be present/);
  assert.match(problems, /browser_specific_settings must not be present/);
  assert.match(problems, /minimum_chrome_version is missing/);
  assert.match(problems, /"contextMenus", not "menus"/);
});

test("checkTargetKeys reports a Chromium manifest offered as the Firefox one", () => {
  const problems = checkTargetKeys("firefox", chromiumManifest(ROOT, OVERLAY), ROOT).join("\n");
  assert.match(problems, /background\.scripts must list/);
  assert.match(problems, /background\.service_worker must not be present/);
  assert.match(problems, /gecko\.id is missing/);
  assert.match(problems, /minimum_chrome_version must not be present/);
});

test("checkTargetKeys reports a version that differs from the root manifest, and an unknown target", () => {
  assert.match(checkTargetKeys("chromium", { ...chromiumManifest(ROOT, OVERLAY), version: "9.9.9" }, ROOT).join("\n"), /version must equal/);
  assert.match(checkTargetKeys("safari", ROOT, ROOT).join("\n"), /unknown target "safari"/);
});

test("duplicateTopLevelNames finds a name declared in two files", () => {
  const found = duplicateTopLevelNames({
    "background/rss.js": "async function fetchWithTimeout(url) {}\n",
    "background/resolve.js": "// helper\nasync function fetchWithTimeout(url) {}\n",
  });
  assert.deepEqual(found, [{ name: "fetchWithTimeout", files: ["background/rss.js", "background/resolve.js"] }]);
});

test("duplicateTopLevelNames ignores indented declarations and a name repeated inside one file", () => {
  const found = duplicateTopLevelNames({
    a: "function f() {\n  function g() {}\n}\nfunction f() {}\n",
    b: "  function f() {}\nconst g = 1;\n",
  });
  assert.deepEqual(found, []);
});

test("duplicateTopLevelNames sees function, async function, generator, const, let, var and class declarations", () => {
  const text = "async function a1() {}\nfunction* g1() {}\nconst c1 = 1;\nlet l1;\nvar v1;\nclass K1 {}\nfunction f1() {}\n";
  const found = duplicateTopLevelNames({ one: text, two: text });
  assert.deepEqual(found.map((entry) => entry.name).sort(), ["K1", "a1", "c1", "f1", "g1", "l1", "v1"]);
});

// A minimal zip writer, just enough to feed readZip. Entries are [name, content, method]: 0 stores, 8 deflates.
function makeZip(entries, comment = "") {
  const parts = [];
  const central = [];
  let offset = 0;
  for (const [name, content, method = 0] of entries) {
    const nameBytes = Buffer.from(name);
    const size = Buffer.byteLength(content);
    const data = method === 8 ? zlib.deflateRawSync(Buffer.from(content)) : Buffer.from(content);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(method, 8);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(size, 22);
    local.writeUInt16LE(nameBytes.length, 26);
    parts.push(local, nameBytes, data);
    const entry = Buffer.alloc(46);
    entry.writeUInt32LE(0x02014b50, 0);
    entry.writeUInt16LE(20, 4);
    entry.writeUInt16LE(20, 6);
    entry.writeUInt16LE(method, 10);
    entry.writeUInt32LE(data.length, 20);
    entry.writeUInt32LE(size, 24);
    entry.writeUInt16LE(nameBytes.length, 28);
    entry.writeUInt32LE(offset, 42);
    central.push(entry, nameBytes);
    offset += 30 + nameBytes.length + data.length;
  }
  const centralBytes = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralBytes.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(Buffer.byteLength(comment), 20);
  return Buffer.concat([...parts, centralBytes, end, Buffer.from(comment)]);
}

test("readZip returns stored and deflated files, skips directory entries, and copes with a zip comment", () => {
  const long = "the same line, repeated so that it deflates well\n".repeat(40);
  const zip = makeZip(
    [
      ["dir/", ""],
      ["a.txt", "hello\n"],
      ["dir/b.txt", long, 8],
      ["dir/ü.txt", "unicode name"],
    ],
    "0e0d4d53bbd5d4a84ff7ac1e5b5c1c3a1e6c5d21" // git writes the commit id here
  );
  const files = readZip(zip);
  assert.deepEqual([...files.keys()], ["a.txt", "dir/b.txt", "dir/ü.txt"]);
  assert.equal(files.get("a.txt").toString(), "hello\n");
  assert.equal(files.get("dir/b.txt").toString(), long);
  assert.equal(files.get("dir/ü.txt").toString(), "unicode name");
});

test("readZip refuses data that is not a zip, a damaged directory and an unsupported compression method", () => {
  assert.throws(() => readZip(Buffer.from("definitely not a zip file, just some text")), PackageError);
  const zip = makeZip([["a.txt", "hi"]]);
  const damaged = Buffer.from(zip);
  damaged[damaged.indexOf(Buffer.from([0x50, 0x4b, 0x01, 0x02]))] = 0;
  assert.throws(() => readZip(damaged), /corrupt zip/);
  assert.throws(() => readZip(makeZip([["a.txt", "hi", 12]])), /unsupported zip compression method 12/);
});
