import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import zlib from "node:zlib";
import {
  PackageError,
  RUNTIME_PATHS,
  USAGE,
  applyOverlay,
  buildDev,
  buildRelease,
  checkTargetKeys,
  chromiumManifest,
  duplicateTopLevelNames,
  main,
  manifestFiles,
  readZip,
  workerEntry,
} from "./package.mjs";

// A manifest shaped like the extension's own, with made-up values, so these tests do not depend on the real one.
const ROOT = {
  manifest_version: 3,
  name: "Example",
  version: "1.2.3",
  icons: { 16: "icons/icon-16.png", 128: "icons/icon-128.png" },
  background: { scripts: ["background/types.js", "background/rss.js", "background/background.js"] },
  content_scripts: [{ matches: ["*://www.example.com/*"], js: ["content/watch.js"], run_at: "document_idle" }],
  action: { default_icon: { 16: "icons/icon-16.png" }, default_title: "Example" },
  options_ui: { page: "options/options.html", open_in_tab: true },
  permissions: ["storage", "menus"],
  host_permissions: ["*://www.example.com/*"],
  browser_specific_settings: { gecko: { id: "example@example.com", strict_min_version: "140.0" } },
};
const OVERLAY = {
  background: { scripts: null, service_worker: "background/service-worker.js" },
  browser_specific_settings: null,
  minimum_chrome_version: "148",
};

test("applyOverlay leaves its arguments alone", () => {
  const base = { a: { b: 1, c: 2 }, list: [1, 2] };
  const overlay = { a: { b: null }, list: [3] };
  const baseBefore = structuredClone(base);
  const overlayBefore = structuredClone(overlay);
  applyOverlay(base, overlay);
  assert.deepEqual(base, baseBefore);
  assert.deepEqual(overlay, overlayBefore);
});

test("applyOverlay merges objects, removes keys set to null, and replaces arrays and scalars", () => {
  const result = applyOverlay({ a: { b: 1, c: 2 }, list: [1, 2], s: "x" }, { a: { b: null, d: 4 }, list: [9], s: "y" });
  assert.deepEqual(result, { a: { c: 2, d: 4 }, list: [9], s: "y" });
});

test("applyOverlay lets an object replace a scalar", () => {
  assert.deepEqual(applyOverlay({ a: 1 }, { a: { b: 2 } }), { a: { b: 2 } });
});

test("chromiumManifest applies the overlay and inherits everything else", () => {
  const manifest = chromiumManifest(ROOT, OVERLAY);
  assert.deepEqual(manifest.background, { service_worker: "background/service-worker.js" });
  assert.equal(manifest.browser_specific_settings, undefined);
  assert.equal(manifest.minimum_chrome_version, "148");
  assert.equal(manifest.version, ROOT.version);
  assert.deepEqual(manifest.host_permissions, ROOT.host_permissions);
  assert.deepEqual(manifest.content_scripts, ROOT.content_scripts);
});

test("chromiumManifest writes the menus permission the way Chrome spells it, once", () => {
  assert.deepEqual(chromiumManifest(ROOT, OVERLAY).permissions, ["storage", "contextMenus"]);
  assert.deepEqual(chromiumManifest({ ...ROOT, permissions: ["storage", "menus", "contextMenus"] }, OVERLAY).permissions, [
    "storage",
    "contextMenus",
  ]);
  assert.equal(chromiumManifest({ ...ROOT, permissions: undefined }, OVERLAY).permissions, undefined);
});

test("workerEntry loads the background scripts, relative to the worker's folder", () => {
  assert.equal(
    workerEntry(ROOT.background.scripts, "background/service-worker.js"),
    '// Generated by tools/package.mjs from "background.scripts" in manifest.json. Do not edit.\n' +
      'importScripts("types.js", "rss.js", "background.js");\n'
  );
  assert.match(workerEntry(["background/a.js", "common/b.js"], "background/sw.js"), /importScripts\("a\.js", "\.\.\/common\/b\.js"\);/);
  assert.match(workerEntry(["background/a.js"], "sw.js"), /importScripts\("background\/a\.js"\);/);
});

test("workerEntry refuses an empty script list and a worker path that is not a .js file", () => {
  assert.throws(() => workerEntry([], "sw.js"), PackageError);
  assert.throws(() => workerEntry(undefined, "sw.js"), PackageError);
  assert.throws(() => workerEntry(["a.js"], "sw.txt"), PackageError);
  assert.throws(() => workerEntry(["a.js"], undefined), PackageError);
});

test("manifestFiles lists every file the manifest refers to, sorted, once", () => {
  assert.deepEqual(manifestFiles(ROOT), [
    "background/background.js",
    "background/rss.js",
    "background/types.js",
    "content/watch.js",
    "icons/icon-128.png",
    "icons/icon-16.png",
    "options/options.html",
  ]);
});

test("manifestFiles also covers a service worker, styles, a popup, a single icon and an options page", () => {
  const files = manifestFiles({
    background: { service_worker: "sw.js", page: "bg.html" },
    content_scripts: [{ js: ["c.js"], css: ["c.css"] }],
    action: { default_icon: "icon.png", default_popup: "popup.html" },
    options_page: "options.html",
  });
  assert.deepEqual(files, ["bg.html", "c.css", "c.js", "icon.png", "options.html", "popup.html", "sw.js"]);
});

test("checkTargetKeys accepts the Firefox manifest and the Chromium manifest derived from it", () => {
  assert.deepEqual(checkTargetKeys("firefox", ROOT, ROOT), []);
  assert.deepEqual(checkTargetKeys("chromium", chromiumManifest(ROOT, OVERLAY), ROOT), []);
});

test("checkTargetKeys reports a Firefox manifest offered as the Chromium one", () => {
  const problems = checkTargetKeys("chromium", ROOT, ROOT).join("\n");
  assert.match(problems, /background\.service_worker is missing/);
  assert.match(problems, /background\.scripts must not be present/);
  assert.match(problems, /browser_specific_settings must not be present/);
  assert.match(problems, /minimum_chrome_version is missing/);
  assert.match(problems, /"contextMenus", not "menus"/);
});

test("checkTargetKeys reports a Chromium manifest offered as the Firefox one", () => {
  const problems = checkTargetKeys("firefox", chromiumManifest(ROOT, OVERLAY), ROOT).join("\n");
  assert.match(problems, /background\.scripts must list/);
  assert.match(problems, /background\.service_worker must not be present/);
  assert.match(problems, /gecko\.id is missing/);
  assert.match(problems, /minimum_chrome_version must not be present/);
});

test("checkTargetKeys reports a version that differs from the root manifest, and an unknown target", () => {
  assert.match(checkTargetKeys("chromium", { ...chromiumManifest(ROOT, OVERLAY), version: "9.9.9" }, ROOT).join("\n"), /version must equal/);
  assert.match(checkTargetKeys("safari", ROOT, ROOT).join("\n"), /unknown target "safari"/);
});

test("duplicateTopLevelNames finds a name declared in two files", () => {
  const found = duplicateTopLevelNames({
    "background/rss.js": "async function fetchWithTimeout(url) {}\n",
    "background/resolve.js": "// helper\nasync function fetchWithTimeout(url) {}\n",
  });
  assert.deepEqual(found, [{ name: "fetchWithTimeout", files: ["background/rss.js", "background/resolve.js"] }]);
});

test("duplicateTopLevelNames ignores indented declarations and a name repeated inside one file", () => {
  const found = duplicateTopLevelNames({
    a: "function f() {\n  function g() {}\n}\nfunction f() {}\n",
    b: "  function f() {}\nconst g = 1;\n",
  });
  assert.deepEqual(found, []);
});

test("duplicateTopLevelNames sees function, async function, generator, const, let, var and class declarations", () => {
  const text = "async function a1() {}\nfunction* g1() {}\nconst c1 = 1;\nlet l1;\nvar v1;\nclass K1 {}\nfunction f1() {}\n";
  const found = duplicateTopLevelNames({ one: text, two: text });
  assert.deepEqual(found.map((entry) => entry.name).sort(), ["K1", "a1", "c1", "f1", "g1", "l1", "v1"]);
});

// A minimal zip writer, just enough to feed readZip. Entries are [name, content, method]: 0 stores, 8 deflates.
function makeZip(entries, comment = "") {
  const parts = [];
  const central = [];
  let offset = 0;
  for (const [name, content, method = 0] of entries) {
    const nameBytes = Buffer.from(name);
    const size = Buffer.byteLength(content);
    const data = method === 8 ? zlib.deflateRawSync(Buffer.from(content)) : Buffer.from(content);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(method, 8);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(size, 22);
    local.writeUInt16LE(nameBytes.length, 26);
    parts.push(local, nameBytes, data);
    const entry = Buffer.alloc(46);
    entry.writeUInt32LE(0x02014b50, 0);
    entry.writeUInt16LE(20, 4);
    entry.writeUInt16LE(20, 6);
    entry.writeUInt16LE(method, 10);
    entry.writeUInt32LE(data.length, 20);
    entry.writeUInt32LE(size, 24);
    entry.writeUInt16LE(nameBytes.length, 28);
    entry.writeUInt32LE(offset, 42);
    central.push(entry, nameBytes);
    offset += 30 + nameBytes.length + data.length;
  }
  const centralBytes = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralBytes.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(Buffer.byteLength(comment), 20);
  return Buffer.concat([...parts, centralBytes, end, Buffer.from(comment)]);
}

test("readZip returns stored and deflated files, skips directory entries, and copes with a zip comment", () => {
  const long = "the same line, repeated so that it deflates well\n".repeat(40);
  const zip = makeZip(
    [
      ["dir/", ""],
      ["a.txt", "hello\n"],
      ["dir/b.txt", long, 8],
      ["dir/ü.txt", "unicode name"],
    ],
    "0e0d4d53bbd5d4a84ff7ac1e5b5c1c3a1e6c5d21" // git writes the commit id here
  );
  const files = readZip(zip);
  assert.deepEqual([...files.keys()], ["a.txt", "dir/b.txt", "dir/ü.txt"]);
  assert.equal(files.get("a.txt").toString(), "hello\n");
  assert.equal(files.get("dir/b.txt").toString(), long);
  assert.equal(files.get("dir/ü.txt").toString(), "unicode name");
});

test("readZip refuses data that is not a zip, a damaged directory and an unsupported compression method", () => {
  assert.throws(() => readZip(Buffer.from("definitely not a zip file, just some text")), PackageError);
  const zip = makeZip([["a.txt", "hi"]]);
  const damaged = Buffer.from(zip);
  damaged[damaged.indexOf(Buffer.from([0x50, 0x4b, 0x01, 0x02]))] = 0;
  assert.throws(() => readZip(damaged), /corrupt zip/);
  assert.throws(() => readZip(makeZip([["a.txt", "hi", 12]])), /unsupported zip compression method 12/);
});

// ---------------------------------------------------------------------------
// Integration tests: each one builds a small throwaway git repository in the OS temp folder, so
// none of them depends on the state of the real repository.
// ---------------------------------------------------------------------------

const FIXTURE_MANIFEST = {
  manifest_version: 3,
  name: "Fixture",
  version: "1.0.0",
  icons: { 16: "icons/icon-16.png" },
  background: { scripts: ["background/a.js", "background/b.js"] },
  content_scripts: [{ matches: ["*://www.example.com/*"], js: ["content/watch.js"] }],
  action: { default_icon: { 16: "icons/icon-16.png" } },
  options_ui: { page: "options/options.html" },
  permissions: ["storage", "menus"],
  browser_specific_settings: { gecko: { id: "fixture@example.com" } },
};
const FIXTURE_OVERLAY = {
  background: { scripts: null, service_worker: "background/service-worker.js" },
  browser_specific_settings: null,
  minimum_chrome_version: "148",
};

const git = (cwd, ...args) =>
  execFileSync(
    "git",
    ["-c", "user.name=Test", "-c", "user.email=test@example.com", "-c", "commit.gpgsign=false", "-c", "core.autocrlf=false", ...args],
    { cwd, stdio: ["ignore", "pipe", "pipe"] }
  );

/** Commits a small extension tree and returns its folder. `change` may edit the files first; a null content skips the file. */
function makeRepo(change = () => {}) {
  const repoRoot = fs.mkdtempSync(path.join(os.tmpdir(), "yt-package-test-"));
  const files = {
    "manifest.json": JSON.stringify(FIXTURE_MANIFEST, null, 2) + "\n",
    "tools/chromium-overlay.json": JSON.stringify(FIXTURE_OVERLAY, null, 2) + "\n",
    "background/a.js": "const A = 1;\n",
    "background/b.js": "function b() {\n  return 2;\n}\n",
    "common/c.js": "// shared\n",
    "content/watch.js": "// content script\n",
    "feed/feed.html": "<!doctype html>\n",
    "icons/icon-16.png": Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x00, 0xff, 0x0d, 0x0a]),
    "options/options.html": "<!doctype html>\n",
    "LICENSE.txt": "licence text\n",
    "README.md": "not part of any package\n",
  };
  change(files);
  for (const [name, content] of Object.entries(files)) {
    if (content === null) continue;
    fs.mkdirSync(path.dirname(path.join(repoRoot, name)), { recursive: true });
    fs.writeFileSync(path.join(repoRoot, name), content);
  }
  git(repoRoot, "init", "-q");
  git(repoRoot, "add", "-A");
  git(repoRoot, "commit", "-q", "-m", "fixture");
  return repoRoot;
}

const PACKAGE_FILES = [
  "LICENSE.txt",
  "background/a.js",
  "background/b.js",
  "common/c.js",
  "content/watch.js",
  "feed/feed.html",
  "icons/icon-16.png",
  "manifest.json",
  "options/options.html",
];
const zipFiles = (zipPath) => readZip(fs.readFileSync(zipPath));
const distFiles = (repoRoot) => (fs.existsSync(path.join(repoRoot, "dist")) ? fs.readdirSync(path.join(repoRoot, "dist")) : []);

test("the Firefox package is byte for byte what plain `git archive` produces", () => {
  const repoRoot = makeRepo();
  const result = buildRelease({ repoRoot, target: "firefox" });
  const direct = path.join(repoRoot, "direct.zip");
  execFileSync(
    "git",
    ["-c", "core.autocrlf=false", "-c", "core.eol=lf", "archive", "--format=zip", "--output", direct, "HEAD", ...RUNTIME_PATHS],
    { cwd: repoRoot }
  );
  assert.equal(fs.readFileSync(result.outPath).compare(fs.readFileSync(direct)), 0);
  assert.equal(path.basename(result.outPath), "yt-channels-1.0.0-firefox.zip");
  assert.equal(result.version, "1.0.0");
  assert.equal(result.fileCount, PACKAGE_FILES.length);
});

test("the Firefox package holds the runtime files and nothing else", () => {
  const files = zipFiles(buildRelease({ repoRoot: makeRepo(), target: "firefox" }).outPath);
  assert.deepEqual([...files.keys()].sort(), PACKAGE_FILES);
  assert.deepEqual(JSON.parse(files.get("manifest.json")), FIXTURE_MANIFEST);
});

test("the Chromium package is the Firefox package plus a generated worker, with a generated manifest", () => {
  const repoRoot = makeRepo();
  const firefox = zipFiles(buildRelease({ repoRoot, target: "firefox" }).outPath);
  const result = buildRelease({ repoRoot, target: "chromium" });
  const chromium = zipFiles(result.outPath);
  assert.equal(path.basename(result.outPath), "yt-channels-1.0.0-chromium.zip");
  assert.deepEqual([...chromium.keys()].sort(), [...PACKAGE_FILES, "background/service-worker.js"].sort());

  const manifest = JSON.parse(chromium.get("manifest.json"));
  assert.deepEqual(manifest.background, { service_worker: "background/service-worker.js" });
  assert.equal(manifest.browser_specific_settings, undefined);
  assert.equal(manifest.minimum_chrome_version, "148");
  assert.deepEqual(manifest.permissions, ["storage", "contextMenus"]);
  assert.equal(manifest.version, "1.0.0");
  assert.equal(
    chromium.get("background/service-worker.js").toString(),
    '// Generated by tools/package.mjs from "background.scripts" in manifest.json. Do not edit.\nimportScripts("a.js", "b.js");\n'
  );
  for (const [name, content] of firefox) {
    if (name !== "manifest.json") assert.ok(content.equals(chromium.get(name)), `${name} must be identical in both packages`);
  }
});

test("a release refuses a tree with uncommitted changes and writes nothing", () => {
  const repoRoot = makeRepo();
  fs.appendFileSync(path.join(repoRoot, "background/a.js"), "const EDITED = true;\n");
  for (const target of ["firefox", "chromium"]) {
    assert.throws(() => buildRelease({ repoRoot, target }), /uncommitted changes[\s\S]*background\/a\.js/);
  }
  assert.deepEqual(distFiles(repoRoot), []);
});

test("untracked files do not stop a release", () => {
  const repoRoot = makeRepo();
  fs.writeFileSync(path.join(repoRoot, "notes.txt"), "scratch\n");
  assert.ok(fs.existsSync(buildRelease({ repoRoot, target: "firefox" }).outPath));
});

test("a manifest that refers to a file missing from the commit fails the build, and no zip is left behind", () => {
  const repoRoot = makeRepo((files) => {
    files["content/watch.js"] = null;
  });
  for (const target of ["firefox", "chromium"]) {
    assert.throws(() => buildRelease({ repoRoot, target }), /manifest\.json refers to content\/watch\.js/);
  }
  assert.deepEqual(distFiles(repoRoot), []);
});

test("a top-level name declared in two background scripts fails the build for both targets", () => {
  const repoRoot = makeRepo((files) => {
    files["background/a.js"] = "function helper() {}\n";
    files["background/b.js"] = "async function helper() {}\n";
  });
  for (const target of ["firefox", "chromium"]) {
    assert.throws(() => buildRelease({ repoRoot, target }), /"helper" is declared at the top level of both background\/a\.js and background\/b\.js/);
  }
});

test("an overlay that leaves background.scripts in place fails the Chromium build only", () => {
  const repoRoot = makeRepo((files) => {
    files["tools/chromium-overlay.json"] = JSON.stringify({ background: { service_worker: "background/service-worker.js" }, minimum_chrome_version: "148" });
  });
  assert.throws(() => buildRelease({ repoRoot, target: "chromium" }), /background\.scripts must not be present/);
  assert.ok(fs.existsSync(buildRelease({ repoRoot, target: "firefox" }).outPath));
});

test("a Chromium build needs the overlay to be committed; the Firefox build does not", () => {
  const repoRoot = makeRepo((files) => {
    files["tools/chromium-overlay.json"] = null;
  });
  assert.throws(() => buildRelease({ repoRoot, target: "chromium" }), /tools\/chromium-overlay\.json/);
  assert.ok(fs.existsSync(buildRelease({ repoRoot, target: "firefox" }).outPath));
});

test("a committed background/service-worker.js is refused: that file is generated for Chromium", () => {
  const repoRoot = makeRepo((files) => {
    files["background/service-worker.js"] = "// written by hand\n";
  });
  assert.throws(() => buildRelease({ repoRoot, target: "chromium" }), /background\/service-worker\.js is generated/);
});

test("--dev builds an unpacked folder from the working tree, without a commit and without a zip", () => {
  const repoRoot = makeRepo();
  fs.appendFileSync(path.join(repoRoot, "background/a.js"), "const EDITED = true;\n"); // uncommitted on purpose
  const firefox = buildDev({ repoRoot, target: "firefox" });
  assert.equal(firefox.outDir, path.join(repoRoot, "dist", "firefox"));
  assert.match(fs.readFileSync(path.join(firefox.outDir, "background/a.js"), "utf8"), /EDITED/);
  assert.equal(fs.existsSync(path.join(firefox.outDir, "README.md")), false);
  assert.equal(fs.existsSync(path.join(firefox.outDir, "tools")), false);

  const chromium = buildDev({ repoRoot, target: "chromium" });
  const manifest = JSON.parse(fs.readFileSync(path.join(chromium.outDir, "manifest.json"), "utf8"));
  assert.equal(manifest.background.service_worker, "background/service-worker.js");
  assert.ok(fs.existsSync(path.join(chromium.outDir, "background/service-worker.js")));
  assert.deepEqual(distFiles(repoRoot).sort(), ["chromium", "firefox"]);
});

test("--dev replaces a folder left by an earlier build instead of merging into it", () => {
  const repoRoot = makeRepo();
  buildDev({ repoRoot, target: "firefox" });
  fs.writeFileSync(path.join(repoRoot, "dist/firefox/leftover.txt"), "from an earlier build\n");
  buildDev({ repoRoot, target: "firefox" });
  assert.equal(fs.existsSync(path.join(repoRoot, "dist/firefox/leftover.txt")), false);
});

test("a second release build replaces the first zip", () => {
  const repoRoot = makeRepo();
  const first = buildRelease({ repoRoot, target: "firefox" });
  const second = buildRelease({ repoRoot, target: "firefox" });
  assert.equal(first.outPath, second.outPath);
  assert.equal(first.sha256, second.sha256);
  assert.deepEqual(distFiles(repoRoot), ["yt-channels-1.0.0-firefox.zip"]);
});

test("main returns 0 and prints the result for a good build", () => {
  const repoRoot = makeRepo();
  const lines = [];
  assert.equal(main(["firefox"], { repoRoot, log: (line) => lines.push(line), error: () => assert.fail("no error expected") }), 0);
  assert.match(lines.join("\n"), /firefox package from commit [0-9a-f]{7} \(version 1\.0\.0\)[\s\S]*yt-channels-1\.0\.0-firefox\.zip[\s\S]*9 files/);
  const devLines = [];
  assert.equal(main(["chromium", "--dev"], { repoRoot, log: (line) => devLines.push(line), error: () => {} }), 0);
  assert.match(devLines.join("\n"), /development build from the working tree \(not for release\)/);
});

test("main prints usage for --help, and refuses missing, extra and unknown arguments", () => {
  const repoRoot = makeRepo();
  const run = (argv) => {
    const out = [];
    const err = [];
    const code = main(argv, { repoRoot, log: (line) => out.push(line), error: (line) => err.push(line) });
    return { code, out: out.join("\n"), err: err.join("\n") };
  };
  assert.deepEqual(run(["--help"]), { code: 0, out: USAGE, err: "" });
  assert.equal(run([]).code, 1);
  assert.match(run([]).err, /expected exactly one target[\s\S]*Usage:/);
  assert.match(run(["firefox", "chromium"]).err, /expected exactly one target/);
  assert.match(run(["safari"]).err, /unknown target "safari"/);
  assert.match(run(["firefox", "--zip"]).err, /unknown option --zip/);
  assert.deepEqual(distFiles(repoRoot), []);
});

test("main reports a failed build as a plain message and exit code 1", () => {
  const repoRoot = makeRepo();
  fs.appendFileSync(path.join(repoRoot, "background/a.js"), "\n");
  const err = [];
  assert.equal(main(["firefox"], { repoRoot, log: () => {}, error: (line) => err.push(line) }), 1);
  assert.match(err.join("\n"), /^error: tracked files have uncommitted changes/);
});

test("the real command line answers --help with exit code 0 and a bad target with exit code 1", () => {
  const tool = fileURLToPath(new URL("./package.mjs", import.meta.url));
  const help = spawnSync(process.execPath, [tool, "--help"], { encoding: "utf8" });
  assert.equal(help.status, 0);
  assert.match(help.stdout, /Usage: node tools\/package\.mjs/);
  const bad = spawnSync(process.execPath, [tool, "safari"], { encoding: "utf8" });
  assert.equal(bad.status, 1);
  assert.match(bad.stderr, /unknown target "safari"/);
});
