// Packaging tool for the extension. This first part holds the helpers that need no git and no
// files, so they can be tested alone; the command line is built on top of them.
import path from "node:path";
import zlib from "node:zlib";

/** A failure the user can act on: printed as a plain message, exit code 1. */
export class PackageError extends Error {}

const isPlainObject = (value) => value !== null && typeof value === "object" && !Array.isArray(value);

/**
 * Applies an overlay to a manifest without changing either argument. Objects merge key by
 * key, `null` removes a key, anything else (arrays and scalars included) replaces the value.
 */
export function applyOverlay(base, overlay) {
  const result = structuredClone(base);
  const apply = (target, source) => {
    for (const [key, value] of Object.entries(source)) {
      if (value === null) delete target[key];
      else if (isPlainObject(value) && isPlainObject(target[key])) apply(target[key], value);
      else target[key] = structuredClone(value);
    }
  };
  apply(result, overlay);
  return result;
}

/** The Chromium manifest: the overlay applied, and Chrome's name for the menus permission. */
export function chromiumManifest(root, overlay) {
  const manifest = applyOverlay(root, overlay);
  if (Array.isArray(manifest.permissions)) {
    manifest.permissions = [...new Set(manifest.permissions.map((p) => (p === "menus" ? "contextMenus" : p)))];
  }
  return manifest;
}

/** The text of the service-worker entry: it loads the background scripts the manifest lists for Firefox. */
export function workerEntry(scripts, workerPath) {
  if (!Array.isArray(scripts) || scripts.length === 0 || scripts.some((s) => typeof s !== "string")) {
    throw new PackageError("background.scripts must be a non-empty list of file names");
  }
  if (typeof workerPath !== "string" || !workerPath.endsWith(".js")) {
    throw new PackageError("background.service_worker must be the path of a .js file");
  }
  const dir = path.posix.dirname(workerPath);
  const list = scripts.map((script) => JSON.stringify(path.posix.relative(dir, script))).join(", ");
  return (
    '// Generated by tools/package.mjs from "background.scripts" in manifest.json. Do not edit.\n' +
    `importScripts(${list});\n`
  );
}

/** Every package file a manifest refers to, sorted. Covers the keys this extension uses. */
export function manifestFiles(manifest) {
  const files = new Set();
  const add = (value) => {
    if (typeof value === "string") files.add(value);
  };
  const addAll = (list) => {
    if (Array.isArray(list)) list.forEach(add);
  };
  const addValues = (object) => {
    if (isPlainObject(object)) Object.values(object).forEach(add);
  };
  const background = manifest.background ?? {};
  addAll(background.scripts);
  add(background.service_worker);
  add(background.page);
  for (const contentScript of manifest.content_scripts ?? []) {
    addAll(contentScript.js);
    addAll(contentScript.css);
  }
  addValues(manifest.icons);
  const action = manifest.action ?? {};
  if (typeof action.default_icon === "string") add(action.default_icon);
  else addValues(action.default_icon);
  add(action.default_popup);
  add(manifest.options_ui?.page);
  add(manifest.options_page);
  return [...files].sort();
}

/** Problems with a package manifest for one target; an empty list means it is fine. */
export function checkTargetKeys(target, manifest, root) {
  const problems = [];
  const background = manifest.background ?? {};
  if (manifest.manifest_version !== 3) problems.push("manifest_version must be 3");
  if (typeof manifest.version !== "string" || manifest.version !== root.version) {
    problems.push(`version must equal the root manifest's (${root.version})`);
  }
  if (target === "firefox") {
    if (!Array.isArray(background.scripts) || background.scripts.length === 0) {
      problems.push("Firefox: background.scripts must list the background scripts");
    }
    if (background.service_worker !== undefined) problems.push("Firefox: background.service_worker must not be present");
    if (typeof manifest.browser_specific_settings?.gecko?.id !== "string") {
      problems.push("Firefox: browser_specific_settings.gecko.id is missing");
    }
    if (manifest.minimum_chrome_version !== undefined) problems.push("Firefox: minimum_chrome_version must not be present");
  } else if (target === "chromium") {
    if (typeof background.service_worker !== "string") problems.push("Chromium: background.service_worker is missing");
    if (background.scripts !== undefined) problems.push("Chromium: background.scripts must not be present");
    if (manifest.browser_specific_settings !== undefined) {
      problems.push("Chromium: browser_specific_settings must not be present");
    }
    if (typeof manifest.minimum_chrome_version !== "string") problems.push("Chromium: minimum_chrome_version is missing");
    if (manifest.permissions?.includes("menus")) problems.push('Chromium: the permission must be "contextMenus", not "menus"');
  } else {
    problems.push(`unknown target "${target}"`);
  }
  return problems;
}

// A declaration at the start of a line: function, async function, generator, const, let, var or class.
const DECLARATION = /^(?:(?:async\s+)?function\s*\*?\s*([A-Za-z_$][\w$]*)|(?:const|let|var|class)\s+([A-Za-z_$][\w$]*))/;

/**
 * Top-level names declared in more than one of the given sources ({ "path": "text" }).
 * Background scripts share one global scope, so a second declaration silently replaces
 * the first (or, for const/let/class, fails at load).
 */
export function duplicateTopLevelNames(sources) {
  const declaredIn = new Map();
  for (const [file, text] of Object.entries(sources)) {
    const names = new Set();
    for (const line of text.split(/\r?\n/)) {
      const match = DECLARATION.exec(line);
      if (match) names.add(match[1] ?? match[2]);
    }
    for (const name of names) declaredIn.set(name, [...(declaredIn.get(name) ?? []), file]);
  }
  return [...declaredIn]
    .filter(([, files]) => files.length > 1)
    .map(([name, files]) => ({ name, files }));
}

/** Reads a zip held in memory and returns its files (not its directories) as a Map of name → Buffer. */
export function readZip(buffer) {
  const END = 0x06054b50;
  const CENTRAL = 0x02014b50;
  const LOCAL = 0x04034b50;
  let end = -1;
  // The end-of-central-directory record is last, but a zip comment (git writes the commit id) may follow it.
  for (let i = buffer.length - 22; i >= Math.max(0, buffer.length - 22 - 0xffff); i--) {
    if (buffer.readUInt32LE(i) === END) {
      end = i;
      break;
    }
  }
  if (end < 0) throw new PackageError("not a zip file: no end-of-central-directory record");
  const count = buffer.readUInt16LE(end + 10);
  let offset = buffer.readUInt32LE(end + 16);
  const files = new Map();
  for (let n = 0; n < count; n++) {
    if (buffer.readUInt32LE(offset) !== CENTRAL) throw new PackageError("corrupt zip: bad central directory entry");
    const method = buffer.readUInt16LE(offset + 10);
    const compressedSize = buffer.readUInt32LE(offset + 20);
    const nameLength = buffer.readUInt16LE(offset + 28);
    const extraLength = buffer.readUInt16LE(offset + 30);
    const commentLength = buffer.readUInt16LE(offset + 32);
    const localOffset = buffer.readUInt32LE(offset + 42);
    const name = buffer.toString("utf8", offset + 46, offset + 46 + nameLength);
    offset += 46 + nameLength + extraLength + commentLength;
    if (name.endsWith("/")) continue;
    if (buffer.readUInt32LE(localOffset) !== LOCAL) throw new PackageError(`corrupt zip: bad local header for ${name}`);
    const dataStart = localOffset + 30 + buffer.readUInt16LE(localOffset + 26) + buffer.readUInt16LE(localOffset + 28);
    const raw = buffer.subarray(dataStart, dataStart + compressedSize);
    if (method === 0) files.set(name, raw);
    else if (method === 8) files.set(name, zlib.inflateRawSync(raw));
    else throw new PackageError(`unsupported zip compression method ${method} for ${name}`);
  }
  return files;
}
